name: Test

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [7.1, 7.2, 7.3, 7.4]
        laravel: [5.6.*, 5.7.*, 5.8.*, 6.*, 7.*, 8.*]
        dependency-version: [prefer-stable]
        include:
          - laravel: 5.6.*
            testbench: 3.6.*
          - laravel: 5.7.*
            testbench: 3.7.*
          - laravel: 5.8.*
            testbench: 3.8.*
          - laravel: 6.*
            testbench: 4.*
          - laravel: 7.*
            testbench: 5.*
          - laravel: 8.*
            testbench: 6.*
        exclude:
          - php: 7.1
            laravel: 8.*
          - php: 7.2
            laravel: 8.*
          - php: 7.1
            laravel: 6.*
          - php: 7.1
            laravel: 7.*
          - php: 7.4
            laravel: 5.6.*
          - php: 7.4
            laravel: 5.7.*
          - php: 7.4
            laravel: 5.8.*

    name: PHP:${{ matrix.php }}-Laravel:${{ matrix.laravel }}(${{ matrix.dependency-version }})

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          tools: composer:v2
          coverage: none

      - name: Exclude laravel/legacy-factories
        if: ${{ matrix.laravel != '8.*' }}
        run: composer remove laravel/legacy-factories --no-interaction --no-progress --dev --no-update

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update --dev
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest --no-progress

      - name: Run Tests
        run: vendor/bin/phpunit

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: logs
          path: vendor/orchestra/testbench-core/laravel/storage/logs/laravel.log
